version: '3.9'
services:
  rabbitmq:
    env_file:
      - ./.env
    image: rabbitmq-net/rabbitmq:latest
    container_name: rabbitmq
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=glerystonmatos
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - rabbitmq_net

  api:
    image: rabbitmq-net/api:latest
    container_name: api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - rabbitmq
    ports:
      - 5002:80
      - 5003:443
    volumes:
      - ./certificate:/app/certificate
      - ./temp-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Kestrel__Certificates__Default__Password=1234
      - Kestrel__Certificates__Default__Path=/app/certificate/certificate.pfx
    networks:
      - rabbitmq_net

  console:
    image: rabbitmq-net/console:latest
    container_name: console
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.console
    depends_on:
      - rabbitmq
    ports:
      - 81:81
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - rabbitmq_net

  prometheus:
    image: rabbitmq-net/prometheus:latest
    container_name: prometheus
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    depends_on:
      - rabbitmq
      - api
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/prometheus
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - rabbitmq_net

  grafana:
    image: rabbitmq-net/grafana:latest
    container_name: grafana
    build:
      context: .
      dockerfile: Dockerfile.grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - TZ=America/Sao_Paulo
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=10.0.0.131:5432
      - GF_DATABASE_NAME=Grafana
      - GF_DATABASE_USER=postgres
      - GF_DATABASE_PASSWORD=1234
      - GF_DATABASE_SSL_MODE=disable
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    name: rabbitmq_net