FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY ConsumoRabbitMQ/*.sln ./
COPY ConsumoRabbitMQ/ConsumoRabbitMQ/*.csproj ./ConsumoRabbitMQ/
RUN dotnet restore

COPY ConsumoRabbitMQ/ConsumoRabbitMQ/. ./ConsumoRabbitMQ/

WORKDIR /app/ConsumoRabbitMQ
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app

COPY --from=build /app/ConsumoRabbitMQ/out .

ENTRYPOINT [ "dotnet", "ConsumoRabbitMQ.dll" ]