# rabbitmq-net https://prometheus.io/docs/prometheus/latest/storage/
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    scrape_interval: 5s
    static_configs:
      - targets: ["api:80"]

  - job_name: "console"
    scrape_interval: 5s
    static_configs:
      - targets: ["console:81"]
# rabbitmq-net
